config/routes.rb
Rails.application.routes.draw do
  
  resources :search_engines
  resources :categories
  resources :base_products
  resources :configurations
  resources :case_files
  resources :publication_groups
  resources :customers
  resources :people
  resources :publication_snapshots
  resources :suitcases
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  devise_for :users
  resources :publishers
  resources :products
  resources :publications
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]

  root :to => redirect('/admin')

  # api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :brands, only: [:index, :create, :show, :update, :destroy]
      resources :configurations, only: [:show]
    end
  end
end

app/models/publication_snapshot.rb
class PublicationSnapshot < ApplicationRecord
  belongs_to :publication

  mount_uploader :snapshot, SnapshotUploader

end

app/controllers/publication_snapshots_controller.rb
class PublicationSnapshotsController < InheritedResources::Base

  private

    def publication_snapshot_params
      params.require(:publication_snapshot).permit()
    end
end

app/helpers/publication_snapshots_helper.rb
module PublicationSnapshotsHelper
end

app/views/publication_snapshots/_form.html.erb
<%= form_for(publication_snapshot) do |f| %>
  <% if publication_snapshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication_snapshot.errors.count, "error") %> prohibited this publication_snapshot from being saved:</h2>

      <ul>
      <% publication_snapshot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publication_snapshots/edit.html.erb
<h1>Editing Item Record Snapshot</h1>

<%= render 'form', publication_snapshot: @publication_snapshot %>

<%= link_to 'Show', @publication_snapshot %> |
<%= link_to 'Back', publication_snapshots_path %>

app/views/publication_snapshots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Record Snapshots</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publication_snapshots.each do |publication_snapshot| %>
      <tr>
        <td><%= link_to 'Show', publication_snapshot %></td>
        <td><%= link_to 'Edit', edit_publication_snapshot_path(publication_snapshot) %></td>
        <td><%= link_to 'Destroy', publication_snapshot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Record Snapshot', new_publication_snapshot_path %>

app/views/publication_snapshots/new.html.erb
<h1>New Item Record Snapshot</h1>

<%= render 'form', publication_snapshot: @publication_snapshot %>

<%= link_to 'Back', publication_snapshots_path %>

app/views/publication_snapshots/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_publication_snapshot_path(@publication_snapshot) %> |
<%= link_to 'Back', publication_snapshots_path %>