config/routes.rb
Rails.application.routes.draw do
  
  resources :search_engines
  resources :categories
  resources :base_products
  resources :configurations
  resources :case_files
  resources :publication_groups
  resources :customers
  resources :people
  resources :publication_snapshots
  resources :suitcases
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  devise_for :users
  resources :publishers
  resources :products
  resources :publications
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]

  root :to => redirect('/admin')

  # api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :brands, only: [:index, :create, :show, :update, :destroy]
      resources :configurations, only: [:show]
    end
  end
end

app/models/publication.rb
include ApplicationHelper
class Publication < ApplicationRecord

  has_and_belongs_to_many :products, -> { uniq }
  
  # has_and_belongs_to_many :brands, -> { uniq }
  accepts_nested_attributes_for :products, :allow_destroy => true

  # belongs_to :product
  belongs_to :publisher
  belongs_to :publication_group
  has_one :search_engine
  
  has_many :publication_snapshots
  accepts_nested_attributes_for :publication_snapshots, :allow_destroy => true

  has_and_belongs_to_many :suitcases
  accepts_nested_attributes_for :suitcases, :allow_destroy => true

  mount_uploader :image, PublicationImageUploader

  ransacker :publication_valid,
    formatter: proc { |selected|
      result = Publication.filter_valid(selected.to_i)
      results = result.map(&:id)
      results = results.present? ? results : nil
    }, splat_params: true do |parent|
    parent.table[:id]
  end

  def self.custom_reviewed_at_search(name)
    # This method should return an ActiveRecord::Relation Object with MyModel objects
    # Put in your complex search logic here
    if name == 0
      objects = Publication.where('reviewed_at IS NULL')
    else
      objects = Publication.where('reviewed_at IS NOT NULL')
    end
    return objects
  end

  
  scope :default_order, -> { 
    active_list
      .valid
      .order_by_default
  }

  scope :order_by_default, -> {
    joins('INNER JOIN `publishers` AS publishers_x ON `publications`.`publisher_id` = `publishers_x`.`id`')
    .order('reviewed_at ASC')
    .order('publishers_x.status DESC')
    .order('publishers_x.stolen_score DESC')
  }

  scope :all_suitcases_equals, ->(input){ self.all_in_suitcases([input]) }
  
  scope :in_person, ->(person) do
    # joining this way because without alias a erros is being thrown
    joins('INNER JOIN `publishers` AS publishers_x ON `publications`.`publisher_id` = `publishers_x`.`id`')
    .where('publishers_x.person_id = ?', person).uniq
  end  

  scope :count_active_by_day, ->() do
    # joining this way because without alias a erros is being thrown
    active.group_by_day(:published_at).count.sort 
  end

  scope :count_valid_by_day, ->() do
    # joining this way because without alias a erros is being thrown
    active.valid.group_by_day(:published_at).count.sort 
  end

  scope :count_all_by_day, ->() do
    # joining this way because without alias a erros is being thrown
    group_by_day(:published_at).count.sort 
  end

  scope :in_suitcases, ->(suitcases) do
    # joining this way because without alias a erros is being thrown
    joins('INNER JOIN `publications_suitcases` AS ps ON `ps`.`publication_id` = `publications`.`id`').where('ps.suitcase_id IN (?)', suitcases).uniq
  end

  def self.all_in_suitcases(suitcases)
    pub_ids = Publication.in_suitcases(suitcases).pluck(:id)

    pub_ids += Publication.where('publications.publication_group_id IN (?)', PublicationGroup.in_suitcases(suitcases).pluck(:id)).pluck(:id)

    publisher_ids = Publisher.in_suitcases(suitcases).pluck(:id)
    publisher_ids += Publisher.in_people(Person.in_suitcases(suitcases).pluck(:id)).pluck(:id)

    pub_ids += Publication.where('publications.publisher_id IN (?)', publisher_ids).pluck(:id)

    Publication.where('publications.id IN (?)', pub_ids).uniq
  end
  
#   scope :in_suitcase, ->(suitcase) do
#     # joining this way because without alias a erros is being thrown
#     query = <<~HEREDOC
#       OUTER JOIN "publications_suitcases" ON "publications_suitcases"."publication_id" = "publications"."id"
#       OUTER JOIN "publishers" ON "publications"."publisher_id" = "publishers"."id"
#       OUTER JOIN "people" ON "people"."id" = "publishers"."person_id"
# HEREDOC
#       joins(query).where("publications_suitcases.suitcase_id = ? OR publishers.suitcase_id = ? OR people.suitcase_id = ?", suitcase, suitcase, suitcase)
#   end

  scope :condition_new, -> { where(condition: ApplicationHelper::USE_STATUS_NEW) }
  scope :inactive, -> { where(active: false).uniq.order_by_default }
  scope :inactive_valid, -> { where(active: false).valid.uniq.order_by_default }
  scope :inactive_expired, -> { where(active: false).expired.uniq.order_by_default }
  scope :active, -> { where(active: true).uniq}
  scope :active_list, -> { where(active: true).uniq.order_by_default}
  scope :active_other, -> { where(other: true).uniq }
  scope :active_multi_prod, -> { where(multi_prod: true).uniq }
  scope :active_new, lambda { self.active.condition_new }
  scope :active_valid, lambda { self.active.valid }
  scope :active_expired, lambda { self.active.expired.order_by_default }

  def self.valid
    sys_scraped_at = Configuration.first.sys_scraped_at
    where('last_seen_at >= ?', sys_scraped_at)
  end

  def self.expired
    sys_scraped_at = Configuration.first.sys_scraped_at
    where('last_seen_at < ? OR last_seen_at IS NULL', sys_scraped_at)
  end

  def review!
    update_attribute(:reviewed_at, Time.zone.now)
  end

  def self.filter_valid(selected)
    sys_scraped_at = Configuration.first.sys_scraped_at
    if selected == 1
      self.where('last_seen_at >= ?', sys_scraped_at);
    elsif selected == 0
      self.where('last_seen_at < ? OR last_seen_at IS NULL', sys_scraped_at);
    else
      nil
    end
  end

  def unreview!
    update_attribute(:reviewed_at, nil)
  end  

  def watch!
    update_attribute(:watch, true)
  end

  def unwatch!
    update_attribute(:watch, false)
  end

  def reviewed?
    not self.reviewed_at.nil?
  end

  def set_status(status)
    update_attribute(:status, status)
  end

  def multi!
    update_attribute(:multi_prod, true)
  end

  def unmulti!
    update_attribute(:multi_prod, false)
  end

  def manual!
    update_attribute(:manual_match, true)
  end
  
  def set_condition(condition)
    update_attribute(:condition, condition)
  end

  def active=(x)
    if self.publication_group.nil?
      super(x)
    else
      super(self.active)
    end
  end

  def activate!
    update_column(:active, true)
  end

  def deactivate!
    update_column(:active, false)
  end

  def multi?
    not self.multi_prod.nil?
  end
  
  def watched?
    not self.watch.nil?
  end

  def products_changed?
    hsh = products.map { |x| x.id}.hash
    @products_hash.present? && (@products_hash != hsh)
  end
  
  def remember_products_hash
    @products_hash = products.map { |x| x.id}.hash
  end

  def to_s
    "#{self.name}"
  end

  def recategorize
    category = Category.joins(brands: {products: :publications}).where(publications: {id: self.id}).first
    puts "Before:".yellow
    puts "\t Category: #{category.name}".yellow
    before_products = ""
    before_brands = ""
    self.products.each do |prod|
      before_products << "#{prod.name},"
      before_brands << "#{prod.brand.name}," unless before_brands.include? "#{prod.brand.name},"
    end
    puts "\t Brand: #{before_brands}".yellow
    puts "\t Products: #{before_products}".yellow
    brand_in_category = set_category(category)
    publication_name = ''
    publication_name = self.name.strip.downcase unless self.name.nil?
    publication_description = ''
    publication_description = self.description.strip.downcase unless self.description.nil?
    checked_with_brand = check_with_brand(publication_name, publication_description, brand_in_category, category)
    pub_products = checked_with_brand[:pub_products]
    pub_brands = checked_with_brand[:pub_brands]
    has_products = set_products(self, pub_products, pub_brands, category)
    puts "\n"
    puts "After: ".red
    puts "Brand with aliases #{pub_brands}".red
    puts "products with aliases #{pub_products}".red
    if has_products
      after_products = ""
      after_brands = ""
      self.products.each do |prod|
        after_products << "#{prod.name},"
        after_brands << "#{prod.brand.name}," unless after_brands.include? "#{prod.brand.name},"
      end
      puts "\t Brand: #{after_brands}".red
      puts "\t Products: #{after_products}".red

      Notification.new(name: "Recategorización",
              description: "Antes: \n\tRubro: #{category.name} \n\tMarca: #{before_brands} \n\tProductos: #{before_products}\n || Despues: \n\tRubro: #{category.name} \n\tMarca: #{after_brands} \n\tProductos: #{after_products}",
              process_uuid: "ID publicación: #{self.id}").save
    else
      Notification.new(name: "Recategorización",
              description: "Antes: \n \tRubro: #{category.name} \n\tMarca: #{before_brands} \n\tProductos: #{before_products}\n|| Despues: Nada cambio",
              process_uuid: "ID publicación: #{self.id}").save
      puts "Nothing changed".blue
    end
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.paginate(page: params[:page])
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Item record was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Item record was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Item record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:name, :product_id, :published_at, :publisher_id, :price, :url_id, :stolen_score, :match_score)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(publication) do |f| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :published_at %>
    <%= f.datetime_select :published_at %>
  </div>

  <div class="field">
    <%= f.label :publisher_id %>
    <%= f.text_field :publisher_id %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :url_id %>
    <%= f.text_field :url_id %>
  </div>

  <div class="field">
    <%= f.label :stolen_score %>
    <%= f.text_field :stolen_score %>
  </div>

  <div class="field">
    <%= f.label :match_score %>
    <%= f.text_field :match_score %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Item Record</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Records</h1>

<%= will_paginate %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product</th>
      <th>Published at</th>
      <th>Publisher</th>
      <th>Price</th>
      <th>Url</th>
      <th>Stolen score</th>
      <th>Match score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.name %></td>
        <td><%= publication.product %></td>
        <td><%= publication.published_at %></td>
        <td><%= publication.publisher %></td>
        <td><%= publication.price %></td>
        <td><%= publication.url %></td>
        <td><%= publication.stolen_score %></td>
        <td><%= publication.match_score %></td>
        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>


<br>

<%= link_to 'New Item Record', new_publication_path %>

app/views/publications/new.html.erb
<h1>New Item Record</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publication.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @publication.product %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @publication.published_at %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @publication.publisher %>
</p>

<p>
  <strong>Price:</strong>
  <%= @publication.price %>
</p>

<p>
  <strong>Url:</strong>
  <%= @publication.url %>
</p>

<p>
  <strong>Stolen score:</strong>
  <%= @publication.stolen_score %>
</p>

<p>
  <strong>Match score:</strong>
  <%= @publication.match_score %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>