config/routes.rb
Rails.application.routes.draw do
  
  resources :search_engines
  resources :categories
  resources :base_products
  resources :configurations
  resources :case_files
  resources :publication_groups
  resources :customers
  resources :people
  resources :publication_snapshots
  resources :suitcases
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  devise_for :users
  resources :publishers
  resources :products
  resources :publications
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]

  root :to => redirect('/admin')

  # api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :brands, only: [:index, :create, :show, :update, :destroy]
      resources :configurations, only: [:show]
    end
  end
end

app/models/case_file.rb
class CaseFile < ApplicationRecord
    
    mount_uploader :file, CaseFilesUploader
    belongs_to :suitcase
end

app/controllers/case_files_controller.rb
class CaseFilesController < InheritedResources::Base

  private

    def case_file_params
      params.require(:case_file).permit(:file, :description)
    end
end

app/helpers/case_files_helper.rb
module CaseFilesHelper
end

app/views/case_files/_form.html.erb
<%= form_for(case_file) do |f| %>
  <% if case_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(case_file.errors.count, "error") %> prohibited this case_file from being saved:</h2>

      <ul>
      <% case_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %>
    <%= f.text_field :file %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/case_files/edit.html.erb
<h1>Editing SuitcasesFile</h1>

<%= render 'form', case_file: @case_file %>

<%= link_to 'Show', @case_file %> |
<%= link_to 'Back', case_files_path %>

app/views/case_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>SuitcasesFiles</h1>

<table>
  <thead>
    <tr>
      <th>File</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @case_files.each do |case_file| %>
      <tr>
        <td><%= case_file.file %></td>
        <td><%= case_file.description %></td>
        <td><%= link_to 'Show', case_file %></td>
        <td><%= link_to 'Edit', edit_case_file_path(case_file) %></td>
        <td><%= link_to 'Destroy', case_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New SuitcasesFile', new_case_file_path %>

app/views/case_files/new.html.erb
<h1>New SuitcasesFile</h1>

<%= render 'form', case_file: @case_file %>

<%= link_to 'Back', case_files_path %>

app/views/case_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File:</strong>
  <%= @case_file.file %>
</p>

<p>
  <strong>Description:</strong>
  <%= @case_file.description %>
</p>

<%= link_to 'Edit', edit_case_file_path(@case_file) %> |
<%= link_to 'Back', case_files_path %>